version: "3"

services:
    apiuser:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./apiuser:/apiuser
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
