# Generated by Django 2.2.6 on 2019-10-22 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('cellphone', models.CharField(default='', max_length=255)),
                ('dni', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=300)),
                ('photo', models.CharField(blank=True, max_length=250)),
                ('type_user', models.IntegerField(choices=[(1, 'create user'), (2, 'contributor user')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryCampaing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TagCampaing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('type_reward', models.IntegerField(choices=[(1, 'donation'), (2, 'contribution')], default=1)),
                ('delivery_data', models.DateTimeField()),
                ('delivery_place', models.CharField(blank=True, max_length=400)),
                ('description', models.CharField(blank=True, max_length=800)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_reward', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_token', models.CharField(blank=True, max_length=255)),
                ('is_expired', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
                ('reward_id', models.IntegerField()),
                ('budget', models.FloatField(blank=True, null=True)),
                ('qty_days', models.IntegerField()),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('video', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('public_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_cond', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('email_2', models.CharField(blank=True, max_length=255)),
                ('b_facebook', models.CharField(blank=True, max_length=255)),
                ('b_twitter', models.CharField(blank=True, max_length=255)),
                ('b_linkedin', models.CharField(blank=True, max_length=255)),
                ('b_instagram', models.CharField(blank=True, max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_representative', models.BooleanField(default=False)),
                ('personal_website', models.CharField(blank=True, max_length=255)),
                ('company_website', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_nit', models.CharField(blank=True, max_length=255)),
                ('company_city', models.CharField(blank=True, max_length=255)),
                ('company_phone', models.CharField(blank=True, max_length=255)),
                ('company_address', models.CharField(blank=True, max_length=300)),
                ('company_email', models.CharField(blank=True, max_length=255)),
                ('company_logo', models.CharField(blank=True, max_length=255)),
                ('company_description', models.CharField(blank=True, max_length=255)),
                ('company_facebook', models.CharField(blank=True, max_length=255)),
                ('company_twitter', models.CharField(blank=True, max_length=255)),
                ('company_linkedin', models.CharField(blank=True, max_length=255)),
                ('company_instagram', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
