# Generated by Django 2.2.6 on 2019-11-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaing',
            old_name='is_compolete',
            new_name='is_complete',
        ),
    ]
