# Generated by Django 2.2.7 on 2019-11-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaing',
            old_name='slug_title',
            new_name='slug',
        ),
    ]
