# Generated by Django 2.2.6 on 2019-11-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191113_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='type_reward',
            field=models.IntegerField(choices=[(1, 'donation'), (2, 'contribution')], default=0),
        ),
    ]
