# Generated by Django 2.2.6 on 2019-11-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191101_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaing',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
