# Generated by Django 2.2.7 on 2019-11-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191121_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaing',
            name='status_campaing',
            field=models.IntegerField(choices=[(0, 'begin'), (1, 'created'), (2, 'revision'), (3, 'public'), (4, 'completed')], default=1),
        ),
    ]
