# Generated by Django 2.2.7 on 2019-11-21 20:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191121_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='campaing',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title'),
        ),
    ]
