# Generated by Django 2.2.6 on 2019-11-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campaing_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaing',
            name='add_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaing',
            name='is_compolete',
            field=models.BooleanField(default=False),
        ),
    ]
