# Generated by Django 2.2.6 on 2019-11-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191103_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaing',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='campaing',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='categorycampaing',
            name='campaing',
            field=models.ManyToManyField(to='core.Campaing'),
        ),
        migrations.AddField(
            model_name='tagcampaing',
            name='campaing',
            field=models.ManyToManyField(to='core.Campaing'),
        ),
    ]
