# Generated by Django 2.2.6 on 2019-11-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191103_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaing',
            name='reward_id',
        ),
        migrations.RemoveField(
            model_name='tagcampaing',
            name='campaing',
        ),
        migrations.AddField(
            model_name='campaing',
            name='tag',
            field=models.ManyToManyField(to='core.TagCampaing'),
        ),
    ]
