# Generated by Django 2.2.6 on 2019-11-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191103_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaing',
            old_name='tag',
            new_name='tags',
        ),
    ]
