# Generated by Django 2.2.7 on 2019-11-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_subcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'approved'), (3, 'deleted')], default=1),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'approved'), (3, 'deleted')], default=1),
        ),
    ]
