# Generated by Django 2.2.6 on 2019-10-10 00:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 0, 58, 5, 58251)),
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_cond', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('email_2', models.CharField(blank=True, max_length=255)),
                ('b_facebook', models.CharField(blank=True, max_length=255)),
                ('b_twitter', models.CharField(blank=True, max_length=255)),
                ('b_linkedin', models.CharField(blank=True, max_length=255)),
                ('b_instagram', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
