# Generated by Django 2.2.6 on 2019-11-06 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191103_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_payment', models.IntegerField(choices=[(1, 'debit'), (2, 'credit'), (3, 'cash')], default=1)),
                ('budget_partial', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campaing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_like', models.IntegerField(default=0)),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campaing')),
            ],
        ),
    ]
