# Generated by Django 2.2.6 on 2019-10-10 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191010_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 1, 2, 22, 901463, tzinfo=utc)),
        ),
    ]
