# Generated by Django 2.2.6 on 2019-10-10 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191010_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 1, 5, 25, 827791, tzinfo=utc)),
        ),
    ]
