# Generated by Django 2.2.6 on 2019-11-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_like_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code_payment',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='status_payment',
            field=models.IntegerField(choices=[(1, 'init'), (2, 'pending'), (3, 'finish'), (4, 'devolution')], default=1),
        ),
    ]
