# Generated by Django 2.2.6 on 2019-10-10 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191010_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 1, 20, 39, 637675, tzinfo=utc)),
        ),
    ]
