# Generated by Django 2.2.6 on 2019-11-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='from_user',
            field=models.IntegerField(default=0),
        ),
    ]
