# Generated by Django 2.2.6 on 2019-10-11 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191010_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 11, 20, 22, 55, 759161, tzinfo=utc)),
        ),
    ]
