# Generated by Django 2.2.6 on 2019-10-11 21:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191011_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 11, 21, 24, 41, 488736, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 11, 21, 24, 41, 482420, tzinfo=utc)),
        ),
    ]
