# Generated by Django 2.2.6 on 2019-10-16 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191015_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='company_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_logo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_nit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='company_website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='is_representative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biography',
            name='personal_website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='biography',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 19, 11, 8, 196961, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='biography',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 16, 19, 11, 8, 196994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 19, 11, 8, 190356, tzinfo=utc)),
        ),
    ]
