# Generated by Django 2.2.6 on 2019-10-16 21:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191016_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 21, 50, 46, 211714, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='biography',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 16, 21, 50, 46, 211744, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 21, 50, 46, 208855, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Campaing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
                ('reward_id', models.IntegerField()),
                ('budget', models.FloatField(blank=True, null=True)),
                ('qty_days', models.IntegerField()),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('video', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
